/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Countdown: typeof import('./components/Countdown.vue')['default']
    Navbar: typeof import('./components/Navbar.vue')['default']
    RadialProgress: typeof import('./components/RadialProgress.vue')['default']
    Settings: typeof import('./components/Settings.vue')['default']
  }
}
